# Generated by Django 3.2.7 on 2021-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13)),
                ('sellpx', models.FloatField(default=1)),
                ('offers', models.IntegerField(default=1)),
                ('ninetyd', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=1)),
                ('asr', models.IntegerField(default=2000000)),
            ],
        ),
        migrations.CreateModel(
            name='IdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(max_length=13)),
                ('sku', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='InoviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.CharField(max_length=13)),
                ('quantity', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('cost', models.FloatField(default=1)),
                ('totalprice', models.FloatField(default=1)),
                ('date', models.DateTimeField()),
                ('wholesaler', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=13)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=1)),
                ('salesfees', models.FloatField(default=0)),
                ('postage', models.FloatField(default=0)),
            ],
        ),
    ]
