# Generated by Django 3.2.7 on 2021-09-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbviz', '0004_alter_invoicedata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkuMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='IdMap',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='invoicedata',
            name='isbn13',
        ),
        migrations.RemoveField(
            model_name='staticdata',
            name='cost',
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbviz.staticdata'),
        ),
        migrations.AddField(
            model_name='invoicedata',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbviz.staticdata'),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='pubdate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='skumap',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbviz.staticdata'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sku',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbviz.skumap'),
        ),
    ]
