# Generated by Django 3.2.7 on 2021-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbviz', '0006_alter_staticdata_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='skumap',
            name='status',
            field=models.CharField(default='Active', max_length=13),
        ),
    ]
