# Generated by Django 3.2.7 on 2021-09-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbviz', '0007_skumap_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='sku',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbviz.staticdata'),
        ),
    ]
